[package]
name = "form"
version = "0.1.0"
authors = ["David McGillicuddy <contact@djmcgill.co.uk>"]

[dependencies]
quote = "0.3"

[dependencies.syn]
version = "0.11.11"
features = ["full", "fold", "printing"]
