on:
  push:
    branches: [ staging, trying, main, workflow-test ]
  pull_request:

name: CI

jobs:
  check:
    name: Cargo check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TARGET: [x86_64-unknown-linux-gnu, x86_64-pc-windows-msvc]

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.TARGET }}

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.TARGET }}

      - run: cargo check --target ${{ matrix.TARGET }}
